backend:
  name: github
  repo: onepiece102057-ai/Otaku247
  branch: main
  base_url: https://github.com
  auth_endpoint: oauth/authorize

display_url: https://onepiece102057-ai.github.io/Otaku247/
logo_url: https://onepiece102057-ai.github.io/Otaku247/imagenes/logo.png

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "noticias"
    label: "Publicar Noticia o Video"
    folder: "_noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen de Portada", name: "image", widget: "image"}
      - {label: "ID de Video YouTube", name: "video_id", widget: "string", required: false}
      - {label: "Cuerpo de la Noticia", name: "body", widget: "markdown"}
